config/routes.rb
Hashdb::Application.routes.draw do

  get 'md5_hashes' => 'md5_hashes#index', :as => :md5_hashes
  get 'md5_hashes/new' => 'md5_hashes#new', :as => :md5_hashes_new
  post 'md5_hashes/paste_hashes' => 'md5_hashes#paste_hashes', :as => :md5_hashes_paste_hashes
  post 'md5_hashes/upload_hashes' => 'md5_hashes#upload_hashes', :as => :md5_hashes_upload_hashes
  post 'md5_hashes/paste_passwords' => 'md5_hashes#paste_passwords', :as => :md5_hashes_paste_passwords
  post 'md5_hashes/upload_passwords' => 'md5_hashes#upload_passwords', :as => :md5_hashes_upload_passwords
  get 'md5_hashes/unsolved' => 'md5_hashes#unsolved', :as => :md5_hashes_unsolved
  get 'md5_hashes/wordlist' => 'md5_hashes#wordlist', :as => :md5_hashes_wordlist
  get 'md5_hashes/stats' => 'md5_hashes#stats', :as => :md5_hashes_stats
  get 'md5_hashes/deleteall' => 'md5_hashes#deleteall', :as => :md5_hashes_deletall
  get 'md5_hashes/:hex_hash' => 'md5_hashes#show', :as => :md5_hash

  get 'hash_lists' => 'hash_lists#index', :as => :hash_lists
  get 'hash_lists/new' => 'hash_lists#new', :as => :hash_lists_new
  post 'hash_lists' => 'hash_lists#create', :as => :hash_lists_create
  get 'hash_lists/:id' => 'hash_lists#show', :as => :hash_list
  put 'hash_lists/:id' => 'hash_lists#update', :as => :hash_list_update
  get 'hash_lists/:id/edit' => 'hash_lists#edit', :as => :hash_list_edit
  delete 'hash_lists/:id' => 'hash_lists#destroy', :as => :hash_list_destory
  post 'hash_lists/:id/upload_hashlist' => 'hash_lists#upload_hashlist', :as => :hash_list_upload_hashlist
  
  resources :users

end

app/models/hash_list.rb
class HashList < ActiveRecord::Base
	attr_accessible :title, :description
	has_many :hash_list_hashes, :dependent => :delete_all

  VALID_MD5_REGEX = /\A([0-9]|[a-f]){32}\z/i

  class << self

    def import_hashes(hashList, hashes)
      hashIds = {}
      hashesSet = Set.new(hashes)
      dedupedHashes = hashesSet.to_a()
      dedupedHashes.in_groups_of(1000, false) { | hash_chunk |
        ActiveRecord::Base.transaction do
          knownHashes = Set.new
          md5hashes = Md5Hash.select("id, hex_hash").order(:hex_hash).find_all_by_hex_hash(hash_chunk)

          md5hashes.each do | hash |
            knownHashes.add(hash.hex_hash)
            hashIds[hash] = hash.id
          end

          newHashes = Set.new(hash_chunk)
          unKnownHashes = newHashes.subtract(knownHashes).to_a()
          unKnownHashes.map! {|x| [x]}
          Md5Hash.import([:hex_hash], unKnownHashes, :validate => false)
          md5hashes = Md5Hash.select("id, hex_hash").order(:hex_hash).find_all_by_hex_hash(hash_chunk)
          md5hashes.each do | hash |
            hashIds[hash] = hash.id
          end
        end
      }


      id = hashList.id
      md5hashes = Md5Hash.find_all_by_hex_hash(dedupedHashes)
      
      md5hashes.map {|hash| hashIds[hash.hex_hash] = hash.id }


      hashes.in_groups_of(5000, false) { | hash_chunk |
        ActiveRecord::Base.transaction do

            listHashes = Array.new
            hash_chunk.each do | hash |
              #md5hash = Md5Hash.find_by_hex_hash(hash)
              listHash = HashListHash.new
              listHash.hash_list_id = id
              #listHash.md5_hash = md5hash
              listHash.md5_hash_id = hashIds[hash]
              listHashes += [listHash]
            end
          HashListHash.import(listHashes)
        end
      }
    end

  	def import_from_file(hashList, file)
  		hashes = Array.new

  		while(hash = file.gets)
        hash.downcase!
        hash.strip!
        if hash.length == 32
          if VALID_MD5_REGEX.match(hash) != nil
       	    hashes += [hash]
          end
        end
     	end

      HashList.import_hashes(hashList, hashes)
  	end
  end
end

app/controllers/hash_lists_controller.rb
class HashListsController < ApplicationController
	def index
		@hashLists = HashList.all
	end

	def new
		@hashList = HashList.new
	end

	def create
		@hashList = HashList.new(params[:hash_list])
		if @hashList.save
			redirect_to hash_list_path(@hashList)
			#render 'show'
		else
			render 'new'
		end
	end

	def show
		@hashList = HashList.find(params[:id])
		offset = params[:offset] || 0
		@hashCount = @hashList.hash_list_hashes.count # HashListHash.where(hash_list_id: @hashList.id).count
		@hashesSolvedCount = @hashList.hash_list_hashes.joins("INNER JOIN md5_hashes ON hash_list_hashes.md5_hash_id = md5_hashes.id").where("md5_hashes.password IS NOT NULL").count
		if @hashList == nil
			render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
		end
		@hashListHashes = @hashList.hash_list_hashes.paginate(:page => params[:page])
	end

	def edit
		@hashList = HashList.find(params[:id])
		if @hashList == nil
			render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
		end
	end

	def upload_hashlist
		t1 = Time.now.to_f
		@hashList = HashList.find(params[:id])
		
		if @hashList
			upload = params[:upload]
			if(upload != nil)
				datafile = upload[:datafile]
				tmpfile = datafile.tempfile
				
				HashList.import_from_file(@hashList, tmpfile)
			end
			t2 = Time.now.to_f
			flash[:notice] = (t2-t1).to_s + " seconds."
			redirect_to hash_list_path @hashList
			#render "show"
		end
	end

	def update
		@hashList = HashList.find(params[:id])
		if @hashList.update_attributes(params[:hash_list])
			redirect_to hash_list_path(@hashList)
		else
			render 'edit'
		end
	end

	def destroy
		@hashList = HashList.find(params[:id])
		@hashList.destroy
		redirect_to hash_lists_path
	end
end

app/views/hash_lists/_footer.html.erb
	</div>
	<div class="panel-footer">
		
	</div>
</div>

app/views/hash_lists/_header.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Hash Lists</h2>


<ul class="nav nav-pills">
	<li class="<%= "active" if params[:action] == "index" %>"><%= link_to "index", hash_lists_path %></li>
	<li class="<%= "active" if params[:action] == "new" %>"><%= link_to "New Hash List", hash_lists_new_path %></li>

</ul>

  </div>

  <div class="panel-body">

app/views/hash_lists/edit.html.erb
<h1>Edit Hash List Information</h1>
<ul>
	<li><%= link_to "Create hash list", hash_lists_new_path %></li>

</ul>

<%= form_for(@hashList) do |f| %>
	<!-- error messages here -->
	<%= f.label :title %>
	<%= f.text_field :title %>
	</br>

	<%= f.label :description %>
	<%= f.text_area :description %>
	</br>

	<%= f.submit "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/hash_lists/index.html.erb
<% provide(:title, "Hash Lists") %>
<%= render 'hash_lists/header' %>

<div class="panel panel-default">
	<div class="panel-body">

		<ul>
			<li><%= link_to "hash lists", hash_lists_path %></li>
			<li><%= link_to "Create hash list", hash_lists_new_path %></li>
		</ul>

		<table class="table table-striped table-bordered monospaced">
			<tr>
				<th>Hash Lists</th>
				<th>Actions</th>
			</tr>

			<% @hashLists.each do |hashList| %>
				<tr class="">
			  		<td><%= link_to hashList.title, hash_list_path(hashList) %></td>
			  		<td><%= link_to "[delete]", hashList, method: :delete, confirm: "You sure?", title: hashList.title %> | <%= link_to "[edit]", hash_list_edit_path(hashList) %></td>
			  	</tr>
			<% end %>
		</table>
	</div>
</div>

<%= render 'hash_lists/footer' %>

app/views/hash_lists/new.html.erb
<% provide(:title, "Hash Lists") %>
<%= render 'hash_lists/header' %>
<div class="panel panel-default">
	<div class="panel-body">

	<h1>New hash list</h1>

	<%= form_for(@hashList) do |f| %>
		<!-- error messages here -->
		<%= f.label :title %>
		<%= f.text_field :title %>
		</br>

		<%= f.label :description %>
		<%= f.text_area :description %>
		</br>

		<%= f.submit "Create", class: "btn btn-large btn-primary" %>
	<% end %>

	</div>
</div>

<%= render 'hash_lists/footer' %>

app/views/hash_lists/show.html.erb
<% provide(:title, "Hash List") %>
<%= render 'hash_lists/header' %>


<div class="panel panel-default">
	<div class="panel-heading">
		<h3><%= @hashList.title %></h3>
	</div>
	<div class="panel-body">


Title: <%= @hashList.title %></br>
Descriptioin: <%= @hashList.description %></br>

<% if @hashCount > 0 %>
	Hashes: <%= @hashCount %></br>
	Hashes Solved <%= @hashesSolvedCount %></br>

	<%= will_paginate @hashListHashes %>

	<table class="table table-striped table-bordered monospaced">
		<tr>
			<th>Hash</th>
			<th>solution</th>
		</tr>

		<% @hashListHashes.each do |hashListHash| %>
			<tr>
				<td><%= link_to hashListHash.md5_hash.hex_hash, hashListHash.md5_hash %></td>
				<td><%= hashListHash.md5_hash.password if hashListHash.md5_hash.password != nil %></td>
		<% end %>
	</table>

<% else %>
	<h2>Upload Hash File</h2>
  	<%= form_tag(hash_list_upload_hashlist_path, :multipart => true) do %>
    	<p><label for="upload_file">Select File</label>
    	<%= file_field 'upload', 'datafile' %></p>
    	<%= submit_tag "Upload" %>
  <% end %>
<% end %>

	</div>
</div>

<%= render 'hash_lists/footer' %>