config/routes.rb
Hashdb::Application.routes.draw do

  get 'md5_hashes' => 'md5_hashes#index', :as => :md5_hashes
  get 'md5_hashes/new' => 'md5_hashes#new', :as => :md5_hashes_new
  post 'md5_hashes/paste_hashes' => 'md5_hashes#paste_hashes', :as => :md5_hashes_paste_hashes
  post 'md5_hashes/upload_hashes' => 'md5_hashes#upload_hashes', :as => :md5_hashes_upload_hashes
  post 'md5_hashes/paste_passwords' => 'md5_hashes#paste_passwords', :as => :md5_hashes_paste_passwords
  post 'md5_hashes/upload_passwords' => 'md5_hashes#upload_passwords', :as => :md5_hashes_upload_passwords
  get 'md5_hashes/unsolved' => 'md5_hashes#unsolved', :as => :md5_hashes_unsolved
  get 'md5_hashes/wordlist' => 'md5_hashes#wordlist', :as => :md5_hashes_wordlist
  get 'md5_hashes/stats' => 'md5_hashes#stats', :as => :md5_hashes_stats
  get 'md5_hashes/deleteall' => 'md5_hashes#deleteall', :as => :md5_hashes_deletall
  get 'md5_hashes/:hex_hash' => 'md5_hashes#show', :as => :md5_hash

  get 'hash_lists' => 'hash_lists#index', :as => :hash_lists
  get 'hash_lists/new' => 'hash_lists#new', :as => :hash_lists_new
  post 'hash_lists' => 'hash_lists#create', :as => :hash_lists_create
  get 'hash_lists/:id' => 'hash_lists#show', :as => :hash_list
  put 'hash_lists/:id' => 'hash_lists#update', :as => :hash_list_update
  get 'hash_lists/:id/edit' => 'hash_lists#edit', :as => :hash_list_edit
  delete 'hash_lists/:id' => 'hash_lists#destroy', :as => :hash_list_destory
  post 'hash_lists/:id/upload_hashlist' => 'hash_lists#upload_hashlist', :as => :hash_list_upload_hashlist
  
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

	<div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">HashDB</a>
        </div>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= "active" if params[:controller] == "md5_hashes" %>"><a href="<%= md5_hashes_path %>">MD5</a></li>
            <li class="<%= "active" if params[:controller] == "hash_lists" %>"><a href="<%= hash_lists_path %>">HashLists</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>


		<% flash.each do |name, msg| %>
		  <% if msg.is_a?(String) %>
		  	<div class="alert alert-warning alert-dismissable">
		  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  		<%= msg %>
		  	</div>
		  <% end %>
		<% end %>

		<%= yield %>

    <hr>
    <%= debug(params) if Rails.env.development? %>
	</div>


<%= javascript_include_tag "application" %>
</body>
</html>